---
title: "US-China-EU-Index-Home"
author: "Elliott Detjen"
date: "3/1/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(grid)
library(rworldmap)
library(readxl)
library(tidyverse)
library(psych)
library(rstanarm)
library(ggpubr)

?cor.test()


# Home .Rmd file for the US-China-EU economic relationship index

```



```{r}

library(readxl)
china_or <- China_Oriented_Weights <- read_excel("China_Oriented_Weights.xlsx") %>%
rename(country = country...1) %>%
  select(country, comp)

ggplot(china_or, aes(x = reorder(country, -comp), y = comp)) +
  geom_col() +
  coord_flip()


china_or2 <- ChinaOr_Final_Data <- read_excel("China_Oriented_Weights_2.xlsx") %>%
  rename(country = country...1) %>%
  select(country, comp) %>%
  drop_na()

ggplot(china_or2, aes(x = reorder(country, -comp), y = comp)) +
  geom_col(fill = "steelblue", alpha = 0.7) +
  coord_flip() +
  theme_classic() +
  labs(x = "European Country", y = "Potential Bilateral Cooperation\n Composite Index Score")



```


```{r}

# Importing Master Dataset

data <- Master_Data_US_China <- read_excel("Master_Data_US-China.xlsx") %>%
  select(nato, bri, demo, oecd, tii_us, c_invest, human, intervention, ec_decline, corruption)


nato <- c(0,1,1,1,0,1,1,1,0,1,1,1,1,0,1,1,1,1,0,1,1,1,1,1,1,1,0,1)
bri <- c(1,0,1,1,1,0,0,1,1,0,0,1,1,0,1,1,1,1,1,0,1,1,1,1,1,0,0,0)
oecd <- c(1,1,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,0,1,1,1,1,1)

  
cor.test(bri, oecd)

scale1 <- data.frame(data)

alpha(scale1)






pca <- princomp(data)

summary(pca)

plot(pca)


fa <- factanal(data, factors = 1, rotation = "varimax")

fa.1 <- factanal(data, factors = 1, rotation = "varimax", scores = "regression")

head(fa.1$scores)


frame <- tibble(scale(data$demo))
frame1 <- tibble(scale(data$nato))


 fit_gs <- stan_glm(data = data,
                       formula = 
                      tii_us ~ nato + oecd + demo,
                       family = gaussian(),
                       refresh = 0)
 
 plot(fit_gs)
 
 fit_gs %>%
   ggplot(aes(x = nato)) +
   geom_point()


```


```{r}

# US-EU TII

trade_dirty <- Trade_Index_Indicator <- read_excel("DataJobID-2128207_2128207_T3.xlsx") %>%
  rename(tii_us = "Trade Intensity Index")

trade_dirty <- trade_dirty %>%
  rename(partner = PartnerISO3) %>%
  rename(country = ReporterName) %>%
  rename(year = Year) %>%
  select(c(partner, tii_us, country, year)) %>%
  mutate(partner = str_replace(partner, pattern = "EU27", 
                                    replacement = "NA")) %>%
  mutate(partner = str_replace(partner, pattern = "USA", 
                                    replacement = "USA"))
  
trade_dirty <- trade_dirty[trade_dirty$partner != "NA", ]

trade <- trade_dirty[trade_dirty$year == 2019, ]

trade %>%
  ggplot(aes(x = country, y = tii_us)) +
  geom_col() +
  theme_linedraw() +
  coord_flip()


# China-EU TII

trade_dirty_cn <- ChinaTII <- read_excel("ChinaTII.xlsx") %>%
    rename(tii_cn = "Trade Intensity Index")

trade_dirty_cn <- trade_dirty_cn %>%
  rename(partner = PartnerISO3) %>%
  rename(country = ReporterName) %>%
  rename(year = Year) %>%
  select(c(partner, tii_cn, country, year)) %>%
  mutate(partner = str_replace(partner, pattern = "EU27", 
                                    replacement = "NA"))
  
trade_dirty_cn <- trade_dirty_cn[trade_dirty_cn$partner != "NA", ]

trade_cn <- trade_dirty_cn[trade_dirty_cn$year == 2019, ]

trade_cn %>%
  ggplot(aes(x = country, y = tii_cn)) +
  geom_col() +
  theme_linedraw() +
  coord_flip()


# Combined TII Indices

comb_trade <- merge(trade, trade_cn, by = "country") 

comb_trade$tii_us <- as.numeric(comb_trade$tii_us) 
comb_trade$tii_cn <- as.numeric(comb_trade$tii_cn) 

comb_trade <- comb_trade %>%
  select(country, year.x, tii_us, tii_cn) %>%
  rename(year = year.x) %>%
  mutate(tii_diff = (tii_us - tii_cn))

comb_trade %>%
  ggplot(aes(x = tii_diff, y = country)) +
  geom_col()

View(comb_trade)

# 1-8 TRADE COMPLEMENTARITY INDEX
# Description: The trade complementarity index indicates to what extent the export profile of the reporter matches, or complements, the import profile of the partner. A high index may indicate that two countries would stand to gain from increased trade, and may be particularly useful in evaluating prospective bilateral or regional trade agreements.



```


```{r}

# Map Experimenting

worldMap <- getMap()

# Member States of the European Union

europeanUnion <- c("Austria","Belgium","Bulgaria","Croatia","Cyprus",
                   "Czech Rep.","Denmark","Estonia","Finland","France",
                   "Germany","Greece","Hungary","Ireland","Italy","Latvia",
                   "Lithuania","Luxembourg","Malta","Netherlands","Poland",
                   "Portugal","Romania","Slovakia","Slovenia","Spain",
                   "Sweden","United Kingdom")

# Select only the index of states member of the E.U.

indEU <- which(worldMap$NAME%in%europeanUnion)

# Extract longitude and latitude border's coordinates of members states of E.U. 
europeCoords <- lapply(indEU, function(i){
  df <- data.frame(worldMap@polygons[[i]]@Polygons[[1]]@coords)
  df$region =as.character(worldMap$NAME[i])
  colnames(df) <- list("long", "lat", "region")
  return(df)
})

europeCoords <- do.call("rbind", europeCoords)

# Add some data for each member
value <- sample(x = seq(1,10,by = 0.1), size = length(europeanUnion),
                replace = TRUE)

europeanUnionTable <- data.frame(country = europeanUnion, value = value)

europeCoords$value <- europeanUnionTable$value[match(europeCoords$region,europeanUnionTable$country)]

# Plot the map

P <- ggplot() + geom_polygon(data = europeCoords, aes(x = long, y = lat, group = region, fill = value),
                             colour = "black", size = 0.1) +
  coord_map(xlim = c(-13, 35),  ylim = c(32, 71))

P <- P + scale_fill_gradient(name = "Willingness for US\nEconomic Cooperation", low = "#FF0000FF", high = "#FFFF00FF", na.value = "grey50") +
  theme_void()


P <- P + theme(#panel.grid.minor = element_line(colour = NA), panel.grid.minor = element_line(colour = NA),
               #panel.background = element_rect(fill = NA, colour = NA),
               axis.text.x = element_blank(),
               axis.text.y = element_blank(), axis.ticks.x = element_blank(),
               axis.ticks.y = element_blank(), axis.title = element_blank(),
               #rect = element_blank(),
               plot.margin = unit(0 * c(-1.5, -1.5, -1.5, -1.5), "lines"))

P


# Credits: https://egallic.fr/en/european-map-using-r/
# Also see: https://geocompr.robinlovelace.net/adv-map.html 

```

